export const OPTION_HELP: Record<string, string> = {
  inline: 'Keeps the calendar always visible in the page instead of opening as a popover.',
  isMobile: 'Opens the calendar as a full-screen modal with a backdrop, suited for touch devices.',
  position:
    'Popover placement relative to the field. First word is the main axis (top/bottom/left/right), second is alignment along the other axis. Ignored when inline or isMobile is on.',
  showEvent: 'DOM events that open the popover calendar. Only applies in popover mode.',
  focus: 'Open the calendar when the field receives focus.',
  click: 'Open the calendar when the field is clicked (left click).',
  mousedown: 'Open the calendar on mousedown (right/left click) on the field.',
  autoClose:
    'Hide the popover after a complete selection: one date, or the second endpoint of a range. In multiple mode it stays open after each day.',
  range: 'Select a start and end date as a single range instead of one day at a time.',
  multiple:
    'Pick more than one date. true allows unlimited dates; a number caps how many can be selected.',
  'multiple limit': 'Maximum number of dates that can be selected when multiple is a number.',
  dynamicRange: 'In range mode, drag the start or end date to adjust the span after selection.',
  multipleSeparator: 'Text placed between formatted dates in the input for range and multiple modes.',
  startDate: 'Which month or period the calendar shows when it first opens.',
  minDate: 'Minimum day the user is allowed to select.',
  maxDate: 'Maximum day the user is allowed to select.',
  'disabledDates (comma-separated)': 'Specific days that cannot be selected, as a comma-separated list.',
  'selectedDates (comma-separated)':
    'Dates pre-selected on init. For range mode use pairs in code; here each entry is one day.',
  showOtherMonths: 'Show trailing and leading days from adjacent months in the day grid.',
  selectOtherMonths: 'Allow selecting those outside-month days when they are visible.',
  moveToOtherMonthsOnSelect: 'Jump the visible month to match a selected day from another month.',
  disableNavWhenOutOfRange:
    'Disable prev/next navigation when the next view would fall outside minDate or maxDate.',
  enableTime: 'Show hour and minute controls alongside the date calendar.',
  onlyTime: 'Time picker only — no date grid. Forces enableTime and disables range and multiple.',
  minHours: 'Lowest hour value on the time slider (0-23).',
  maxHours: 'Highest hour value on the time slider (clamped to 23 at runtime).',
  minMinutes: 'Lowest minute value on the time slider.',
  maxMinutes: 'Highest minute value on the time slider.',
  hoursStep: 'Step size when changing hours on the slider.',
  minutesStep: 'Step size when changing minutes on the slider.',
  view: 'Initial calendar view: day grid, month grid, or year grid.',
  allowedViews: 'Which views the user can drill into. Order defines the drill-down sequence.',
  day: 'Include the day view in allowed navigation.',
  month: 'Include the month view in allowed navigation.',
  year: 'Include the year view in allowed navigation.',
  dayViewCols:
    'Number of day columns per row in the day view (1-7). Affects layout and keyboard navigation.',
  monthViewCount: 'How many month cells are shown in the month view.',
  monthViewRadius: 'How many months before the view anchor appear when the grid is centered.',
  monthViewCols: 'Column count for the month view grid.',
  monthViewRows: 'Row count for the month view grid.',
  yearViewCount: 'How many year cells are shown in the year view.',
  yearViewRadius: 'How many years before the view anchor year appear in the grid.',
  yearViewCols: 'Column count for the year view grid.',
  yearViewRows: 'Row count for the year view grid.',
  locale: 'Calendar language — month names, weekday labels, and ARIA strings.',
  firstDay: 'Weekday index (0 = Sunday … 6 = Saturday) that starts each week row.',
  weekends: 'Weekday indexes styled as weekends (default Saturday and Sunday).',
  'Saturday (6)': 'Mark Saturday (index 6) as a weekend day.',
  'Sunday (0)': 'Mark Sunday (index 0) as a weekend day.',
  format: 'Pattern written into the field after selection (e.g. YYYY-MM-DD). Tokens match the docs.',
  'custom format': 'Custom format string when the preset is set to Custom.',
  monthsField: 'Locale key for short month names in the grid and MMM format token.',
  weekdaysField: 'Locale key for weekday header labels in the day view.',
  'navTitles.day': 'HTML template for the navigation title in day view. Supports format tokens.',
  'navTitles.month': 'HTML template for the navigation title in month view.',
  'navTitles.year': 'HTML template for the navigation title in year view (yyyy1, yyyy2 tokens).',
  'prevHtml (optional)': 'Inner HTML for the previous navigation button. Leave empty for the default chevron.',
  'nextHtml (optional)': 'Inner HTML for the next navigation button. Leave empty for the default chevron.',
  buttons: 'Footer action buttons below the calendar. Today jumps to today; Clear empties the selection.',
};

export function optionHelp(key: string): string | undefined {
  return OPTION_HELP[key];
}
