import defaultLocale from '../locale/en.js';

export default {
  classes: {
    container: 'lp',
    header: 'lp-header',
    nav: 'lp-nav',
    grid: 'lp-grid',
    cell: 'lp-cell',
    cellSelected: 'lp-cell--selected',
    cellDisabled: 'lp-cell--disabled',
    cellToday: 'lp-cell--today',
    cellRange: 'lp-cell--range',
    cellRangeStart: 'lp-cell--range-start',
    cellRangeEnd: 'lp-cell--range-end',
    cellRangePreview: 'lp-cell--range-preview',
    cellRangePreviewMid: 'lp-cell--range-preview-mid',
    cellRangePreviewStartCap: 'lp-cell--range-preview-start-cap',
    cellRangePreviewEndCap: 'lp-cell--range-preview-end-cap',
    cellOutside: 'lp-cell--outside',
    cellWeekend: 'lp-cell--weekend',
    cellFocused: 'lp-cell--focused',
    navButton: 'lp-nav-btn',
    titleButton: 'lp-title-btn',
    timePanel: 'lp-time',
    footer: 'lp-footer',
    popoverPointer: 'lp-popover-pointer lp--pointer',
    viewBody: 'lp-view-body'
  },
  render: { container: null, header: null, nav: null, grid: null, time: null, footer: null },
  navTitles: { days: 'MMMM, <i>yyyy</i>', months: 'yyyy', years: 'yyyy1 - yyyy2' },
  inline: false,
  multiple: false,
  range: false,
  enableTime: false,
  onlyTime: false,
  isMobile: false,
  locale: defaultLocale,
  format: 'YYYY-MM-DD',
  monthsField: 'monthsShort',
  view: 'day',
  showOtherMonths: true,
  selectOtherMonths: true,
  moveToOtherMonthsOnSelect: true,
  disableNavWhenOutOfRange: true,
  multipleSeparator: ', ',
  dynamicRange: true,
  buttons: false,
  showEvent: 'focus',
  closeOnSelect: true,
  prevHtml: '<svg><path d="M17,12 l -5,5 l 5,5"></path></svg>',
  nextHtml: '<svg><path d="M14,12 l 5,5 l -5,5"></path></svg>',
  minHours: 0,
  maxHours: 24,
  minMinutes: 0,
  maxMinutes: 59,
  hoursStep: 1,
  minutesStep: 1,
  position: 'bottom left',
  anchor: null,
  disabledDates: [],
  selectedDates: false,
  weekends: [6, 0]
};
